### ISSUE TITLE
遇到一个关于dnspod选择线路的bug

### ISSUE THREAD

**Issue by anankingdu** [lee1080/CloudflareSpeedTestDDNS#30]
三台服务器不同时间运行，一台线路设置为1(电信)，一台为2(联通)，一台为3(移动)。会出现冲突，当其中一个更新ip后，会把另外两个当中的一个给删掉，而不是在规定线路上更新或者新增。

还有个问题就是。我设置线路为0(默认)。结果给我更新成了境外的线路类型
我用的是docker版本

大佬可以发下捐赠码，我表示一点心意，辛苦大佬维护！

**Comment by lee1080** [comment]
这个问题应该在最新版修复了
