### ISSUE TITLE
感谢辛苦付出！能否优化下，支持多个ip

### ISSUE THREAD

**Issue by hululu1068** [lee1080/CloudflareSpeedTestDDNS#53]
目前我用[原项目](https://github.com/XIU2/CloudflareSpeedTest/blob/master/script/cfst_ddns.sh),配置多个`RECORDS_ID`将多个ip解析到同一域名，防止ip失效。比较遗憾的是没有推送支持。
能否优化下，添加多ip的支持，另外推送消息加上"平均延迟"、"下载速度"。
<img width="207" alt="image" src="https://github.com/lee1080/CloudflareSpeedTestDDNS/assets/68652362/143b520f-823d-4da9-8e2d-1c0efc18999d"> 
<img width="739" alt="image" src="https://github.com/lee1080/CloudflareSpeedTestDDNS/assets/68652362/e446b478-2bfe-4cb4-a6d5-2670dd6e30e4">

**Comment by linntt88** [comment]
别想了，这样改要重构代码，没半天改不好，用白嫖大佬的脚本吧

**Comment by cuiren** [comment]
推送消息加上"平均延迟"、"下载速度"这个可以在cf_ddns_cloudflare.sh里边通过添加变量然后修改对应的代码实现

**Comment by hululu1068** [comment]
> 别想了，这样改要重构代码，没半天改不好，有这个需求的话用白嫖大佬的脚本吧

# 想都不敢想，这辈子估计你也不会有啥出息...😏😏😏
<img width="293" alt="image" src="https://github.com/lee1080/CloudflareSpeedTestDDNS/assets/68652362/8a73dc0c-88a1-4268-ba6f-c21f93f34f38">

**Comment by linntt88** [comment]
> > 别想了，这样改要重构代码，没半天改不好，有这个需求的话用白嫖大佬的脚本吧
> 
> # 想都不敢想，这辈子估计你也不会有啥出息...😏😏😏
> <img alt="image" width="293" src="https://user-images.githubusercontent.com/68652362/275079894-8a73dc0c-88a1-4268-ba6f-c21f93f34f38.png">

自己改就改了，还给别人提issue，几行代码有什么好炫耀的，你有啥出息，学历证摆一下，个税记录摆一下

**Comment by hululu1068** [comment]
> > > 别想了，这样改要重构代码，没半天改不好，有这个需求的话用白嫖大佬的脚本吧
> > 
> > 
> > # 想都不敢想，这辈子估计你也不会有啥出息...😏😏😏
> > <img alt="image" width="293" src="https://user-images.githubusercontent.com/68652362/275079894-8a73dc0c-88a1-4268-ba6f-c21f93f34f38.png">
> 
> 自己改就改了，还给别人提issue，几行代码有什么好炫耀的，你有啥出息，学历证摆一下，个税记录摆一下

傻屌...一边玩去吧

**Comment by linntt88** [comment]
> > > > 别想了，这样改要重构代码，没半天改不好，有这个需求的话用白嫖大佬的脚本吧
> > > 
> > > 
> > > # 想都不敢想，这辈子估计你也不会有啥出息...😏😏😏
> > > <img alt="image" width="293" src="https://user-images.githubusercontent.com/68652362/275079894-8a73dc0c-88a1-4268-ba6f-c21f93f34f38.png">
> > 
> > 
> > 自己改就改了，还给别人提issue，几行代码有什么好炫耀的，你有啥出息，学历证摆一下，个税记录摆一下
> 
> 傻屌...一边玩去吧
百度几行代码就拿出来显摆，真tm要笑死
