### ISSUE TITLE
能否增加更新失败后自动重试次数直到成功

### ISSUE THREAD

**Issue by pingshu** [lee1080/CloudflareSpeedTestDDNS#7]
有时候ip测速正常但是更新失败，能否增加自动重试次数直到成功，还有希望增加"重启插件的时间长短可以自定义"，谢谢

**Comment by lee1080** [comment]
重启插件的时间已经可以自定义了，更新到CF确实对网络环境要求比较高，这里推荐使用dnspod模式，国内的DNS服务商响应更快。
