### ISSUE TITLE
IPV6 一直说更新失败

### ISSUE THREAD

**Issue by ericsunhl** [lee1080/CloudflareSpeedTestDDNS#9]
我是移动IPV6公网然后解析到域名，然后再CloudFlare套了DNS并开启了代理模式。
我在docker里根据confi要求配置好了，ipv6.txt文件看到已经在文件夹里，但运行的时候貌似ipv6都无法正确测试到ip地址。
但如果改成ipv4就可以正确运行并且更新到cloudflare的DNS记录里，不知道问题出在哪里。望解答，谢谢！

**Comment by lee1080** [comment]
我这儿测试没有问题，有可能是你docker的设备没有获取到ipv6，不能进行ipv6测速，兼容性最好的还是使用ipv4。
